### ISSUE TITLE
[Help] ST STM32 platform v12.1.1 or v15.4 ?

### ISSUE THREAD

**Issue by KAPTOHKA** [rommulaner/Anycubic_Vyper_MB_CE_6.1d#4]
ST STM32 platform, Do I need to upgrade to version 15.4 before compiling?
Or work with version 12.1.1 by default?

**Comment by rommulaner** [comment]
I didn't change anything and it worked.

**Comment by KAPTOHKA** [comment]
Yes, both versions work, but the code for the firmware is different...
