### ISSUE TITLE
Thermistor support

### ISSUE THREAD

**Issue by fauks** [rommulaner/Anycubic_Vyper_MB_CE_6.1d#5]
Do you know what type of thermistor this firmware supports?

Not only does my Vyper have a new screen, the thermistor setup is different as well. It has a none threaded hole with a sleeve that the thermistor sets in and a set screw from the side that locks it down. I am having low temp readings with the community firmware. Having to print TPU at 180-185c.

![image](https://user-images.githubusercontent.com/82473060/177588804-e5fb97f7-5b1c-49bb-81e1-4fc51f6a7039.png)

**Comment by rommulaner** [comment]
It's Marlin 2, so you can choose every thermistor that is in there. You just have to edit the configurations an compile it.
